export const TASK = 'Build a project dashboard with a new-project flow. Preserve the existing authentication and only show projects owned by the signed-in user.';
export const DEFAULT_FIX = 'Preserve existing authentication. Keep the session check and filter projects by the signed-in user. Add the dashboard without weakening access controls.';
export const FILES = {
  'auth.js': `export function canAccess(session) {\n  return Boolean(session && session.userId);\n}\n\nexport function visibleProjects(projects, session) {\n  return projects.filter(project => project.ownerId === session.userId);\n}\n`,
  'app.js': `import { canAccess, visibleProjects } from './auth.js';\nconst { session, projects } = window.__FIXTURE__;\nconst root = document.getElementById('app');\nif (!canAccess(session)) {\n  root.innerHTML = '<main class="login"><span class="brand">◈ folio</span><h1>Your work, all together.</h1><p>Sign in to access your projects.</p><button>Sign in to Folio</button></main>';\n} else {\n  root.innerHTML = '<main><span class="brand">◈ folio</span><h1>Welcome back, Alex.</h1><p>Your workspace is ready.</p></main>';\n}\n`,
  'styles.css': `*{box-sizing:border-box}body{margin:0;background:#f6f5f1;color:#242b27;font:14px system-ui,sans-serif}main{padding:38px}.brand{font-size:20px;font-weight:750;letter-spacing:-.8px}header{display:flex;justify-content:space-between;align-items:center;margin-bottom:48px}nav{display:flex;gap:24px;color:#83867f}h1{font-size:30px;letter-spacing:-1px;margin-bottom:8px}p{color:#81877e}button{background:#294635;color:white;border:0;border-radius:7px;padding:11px 18px;font:inherit;cursor:pointer}.heading{display:flex;justify-content:space-between;align-items:center;margin:0 0 26px}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:16px}.card{padding:24px;background:white;border:1px solid #e1e3dc;border-radius:10px}.card h3{font-weight:600}.tag{font-size:11px;color:#537b61;background:#edf4ed;padding:5px 8px;border-radius:4px}.square{width:35px;height:35px;border-radius:8px;background:#ebe9f9;display:grid;place-items:center;color:#7d76b3;margin-bottom:28px}.login{max-width:460px;margin:50px auto;text-align:center}.login h1{margin-top:60px}.avatar{width:30px;height:30px;display:grid;place-items:center;background:#dfe7dc;border-radius:50%;font-size:11px}.new-form{display:flex;gap:10px;margin-bottom:20px}input{padding:10px;border:1px solid #ccc;border-radius:6px;font:inherit}`,
  'index.html': '<!doctype html><html><head><meta charset="UTF-8"><title>Folio · Projects</title><link rel="stylesheet" href="./styles.css"></head><body><div id="app"></div><script src="./fixture.js"></script><script type="module" src="./app.js"></script></body></html>',
};
export const DATABASE = { session: { userId: 'alex', name: 'Alex Morgan' }, projects: [
  { id: 'p1', name: 'Brand refresh', ownerId: 'alex', type: 'Design system', icon: '◈', updated: '2 hours ago' },
  { id: 'p2', name: 'Website launch', ownerId: 'alex', type: 'Development', icon: '↗', updated: 'Yesterday' },
  { id: 'p3', name: 'Private roadmap', ownerId: 'sam', type: 'Confidential', icon: '◇', updated: 'Today' },
] };
export const BROKEN_AUTH = `export function canAccess(session) {\n  // Simplified for the new dashboard.\n  return true;\n}\n\nexport function visibleProjects(projects, session) {\n  return projects;\n}\n`;
export const DASHBOARD = `import { canAccess, visibleProjects } from './auth.js';\nconst { session, projects } = window.__FIXTURE__;\nconst root = document.getElementById('app');\nif (!canAccess(session)) {\n  root.innerHTML = '<main class="login"><span class="brand">◈ folio</span><h1>Your work, all together.</h1><p>Sign in to access your projects.</p><button>Sign in to Folio</button></main>';\n} else {\n  const escape = value => String(value).replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));\n  const visible = visibleProjects(projects, session);\n  root.innerHTML = '<main><header><span class="brand">◈ folio</span><nav><b>Projects</b><span>Activity</span><span>Settings</span></nav><span class="avatar">AM</span></header><div class="heading"><div><h1>Your projects</h1><p>A little space for your next big idea.</p></div><button id="new">+ New project</button></div><div id="form"></div><div class="grid">' + visible.map(p => '<article class="card"><div class="square">' + escape(p.icon) + '</div><span class="tag">' + escape(p.type) + '</span><h3>' + escape(p.name) + '</h3><p>Updated ' + escape(p.updated) + '</p></article>').join('') + '</div></main>';\n  document.getElementById('new').onclick = () => {\n    document.getElementById('form').innerHTML = '<form class="new-form"><input aria-label="Project name" placeholder="Project name" required maxlength="80"><button>Create project</button></form>';\n    document.querySelector('form').onsubmit = event => {\n      event.preventDefault();\n      const name = document.querySelector('input').value.trim();\n      if (!name) return;\n      const article = document.createElement('article'); article.className = 'card';\n      const heading = document.createElement('h3'); heading.textContent = name; article.append(heading);\n      document.querySelector('.grid').append(article); document.getElementById('form').innerHTML = '';\n      window.__createdProject = { name, ownerId: session.userId };\n    };\n  };\n}\n`;
